// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TigerTix.Web.Data;

#nullable disable

namespace TigerTix.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241104013608_addedMoreEvents")]
    partial class addedMoreEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TigerTix.Web.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableTickets")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organizer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableTickets = 250,
                            Category = "Sports",
                            Date = new DateTime(2024, 11, 13, 20, 36, 8, 592, DateTimeKind.Local).AddTicks(4830),
                            Description = "Watch the top teams battle for the championship!",
                            ImageUrl = "https://images.unsplash.com/photo-1517649763962-0c623066013b?q=80&w=2748&auto=format&fit=crop",
                            Location = "Staples Center",
                            Name = "Championship Basketball Game",
                            Organizer = "NBA",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 2,
                            AvailableTickets = 500,
                            Category = "Concert",
                            Date = new DateTime(2024, 11, 23, 20, 36, 8, 592, DateTimeKind.Local).AddTicks(4870),
                            Description = "Experience live performances by the best country artists.",
                            ImageUrl = "https://images.unsplash.com/photo-1534230299580-8d82f20a72bc?q=80&w=2748&auto=format&fit=crop",
                            Location = "Nashville Fairgrounds",
                            Name = "Country Music Festival",
                            Organizer = "Country Fest Inc.",
                            Price = 85.00m
                        },
                        new
                        {
                            Id = 3,
                            AvailableTickets = 1000,
                            Category = "Sports",
                            Date = new DateTime(2024, 11, 18, 20, 36, 8, 592, DateTimeKind.Local).AddTicks(4880),
                            Description = "The most anticipated match of the year!",
                            ImageUrl = "https://images.unsplash.com/photo-1594853108080-e9043c5ab3b9?q=80&w=2748&auto=format&fit=crop",
                            Location = "Old Trafford Stadium",
                            Name = "Soccer League Finals",
                            Organizer = "Premier League",
                            Price = 150.00m
                        },
                        new
                        {
                            Id = 4,
                            AvailableTickets = 750,
                            Category = "Concert",
                            Date = new DateTime(2024, 11, 28, 20, 36, 8, 592, DateTimeKind.Local).AddTicks(4880),
                            Description = "Join legendary bands for an unforgettable night of rock.",
                            ImageUrl = "https://images.unsplash.com/photo-1519750157634-baefa305b64e?q=80&w=2748&auto=format&fit=crop",
                            Location = "Madison Square Garden",
                            Name = "Rock & Roll All Night",
                            Organizer = "Live Nation",
                            Price = 100.00m
                        },
                        new
                        {
                            Id = 5,
                            AvailableTickets = 1200,
                            Category = "Sports",
                            Date = new DateTime(2024, 11, 8, 20, 36, 8, 592, DateTimeKind.Local).AddTicks(4880),
                            Description = "Don't miss the most thrilling game of the season.",
                            ImageUrl = "https://images.unsplash.com/photo-1571019613454-1cb2f3d58a00?q=80&w=2748&auto=format&fit=crop",
                            Location = "Levi's Stadium",
                            Name = "Football Championship",
                            Organizer = "NFL",
                            Price = 200.00m
                        },
                        new
                        {
                            Id = 6,
                            AvailableTickets = 400,
                            Category = "Concert",
                            Date = new DateTime(2024, 12, 3, 20, 36, 8, 592, DateTimeKind.Local).AddTicks(4880),
                            Description = "A soulful evening with the best jazz and blues musicians.",
                            ImageUrl = "https://images.unsplash.com/photo-1601285377181-9f2165fb4cd7?q=80&w=2748&auto=format&fit=crop",
                            Location = "New Orleans Jazz Hall",
                            Name = "Jazz & Blues Night",
                            Organizer = "Jazz Fest",
                            Price = 60.00m
                        },
                        new
                        {
                            Id = 7,
                            AvailableTickets = 1300,
                            Category = "Sports",
                            Date = new DateTime(2024, 11, 11, 20, 36, 8, 592, DateTimeKind.Local).AddTicks(4890),
                            Description = "Witness history in the making at the Baseball World Series.",
                            ImageUrl = "https://images.unsplash.com/photo-1581046931477-4a1cb97202c4?q=80&w=2748&auto=format&fit=crop",
                            Location = "Yankee Stadium",
                            Name = "Baseball World Series",
                            Organizer = "MLB",
                            Price = 250.00m
                        },
                        new
                        {
                            Id = 8,
                            AvailableTickets = 350,
                            Category = "Concert",
                            Date = new DateTime(2024, 11, 21, 20, 36, 8, 592, DateTimeKind.Local).AddTicks(4890),
                            Description = "A night of elegance with world-renowned classical musicians.",
                            ImageUrl = "https://images.unsplash.com/photo-1561016444-1ac4435a0ee4?q=80&w=2748&auto=format&fit=crop",
                            Location = "Carnegie Hall",
                            Name = "Classical Music Gala",
                            Organizer = "Classical Society",
                            Price = 75.00m
                        });
                });

            modelBuilder.Entity("TigerTix.Web.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsStudentAccount")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
